name: Star event workflow

on:
  push: 
    branches:
        - main

jobs:
    #that the name of jobs
    example-jop:
        runs-on: ubuntu-latest
        
        steps: 
            - name: print welcome message
              run: echo "wecome to action" 

            - name: checkout of repo
              uses: actions/checkout@v6.0.2
            
            - name: list repo files
              run: ls -la
